#Experiment task
tasks:
    - name: create test user
      user:
        name: "testuser"
        createhome: yes
        state: present
        register: newuser
    - name: generate random password for user only on creation
    shell: /usr/bin/openssl rand -base64 32 | passwd --stdin testuser
    when: newuser.changed

    - name: Configure the Timezone
  hosts: all
  tasks:

    - name: Update Timezone to Asia/Kolkata
      copy: content="Asia/Kolkata\n" dest=/etc/timezone owner=root group=root mode=0644
      sudo: true
      register: timezone

    - name: Reconfigure Timezone Data
      shell: dpkg-reconfigure -f noninteractive tzdata
      sudo: true
      when: timezone.changed
- hosts: blocks
  tasks:
  - name: Ansible copy file to remote server
    copy:
      src: /testuser/examples/testuser.yml
      dest: /home/testuser
- name: Install base packages
  apt: name={{ item }} state=installed
  with_items:
    - locales
    - build-essential
    - htop
    - git
    - supervisor
    - python-pip
    - python3-pip
  tags:
    - packages

- name: Upgrade pip
  pip: name=pip state=latest
  tags:
    - packages
- hosts: consul-server

  vars:
    consul_version: 0.9.2
    consul_server_ip: 10.0.15.10
    consul_config_dir: /etc/systemd/system/consul.d

  tasks:

   - name: Install unzip
     apt: name=unzip state=present
     become: true

   - name: Install Consul
     become: true
     unarchive:
       src: https://releases.hashicorp.com/consul/{{ consul_version }}/consul_{{ consul_version }}_linux_amd64.zip
       remote_src: yes
       dest: /usr/local/bin
       creates: /usr/local/bin/consul
       mode: 0555

   - name: Make Consul a service
     become: true
     copy:
       src: consul.service
       dest: /etc/systemd/system/consul.service

   - name: Ensure config directory exists
     become: true
     file:
       path: "{{ consul_config_dir }}"
       state: directory

   - name: Deploy consul config
     become: true
     template:
       src: init.json.j2
       dest: "{{consul_config_dir}}/init.json"

   - name: Ensure consul's running
     become: true
     service: name=consul state=started
